module.exports = {
    PREFIX: '!',
    AATROX:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Aatrox.png',
    AHRI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Ahri.png',
    AKALI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Akali.png',
    AKSHAN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Akshan.png',
    ALISTAR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Alistar.png',
    AMUMU:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Amumu.png',
    ANIVIA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Anivia.png',
    ANNIE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Annie.png',
    APHELIOS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Aphelios.png',
    ASHE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Ashe.png',
    AURELIONSOL:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Aurelion.png',
    AZIR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Azir.png',
    BARD:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Bard.png',
    BLITZCRANK:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Blitzcrank.png',
    BRAND:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Brand.png',
    BRAUM:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Braum.png',
    CAITLYN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Caitlyn.png',
    CAMILLE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Camille.png',
    CASSIOPEIA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Cassiopeia.png',
    CHOGATH:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/ChoGath.png',
    CORKI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Corki.png',
    DARIUS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Darius.png',
    DIANA:
      `https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Diana.png`,
    DRMUNDO:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/DrMundo.png',
    DRAVEN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Draven.png',
    EKKO:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Ekko.png',
    ELISE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Elise.png',
    EVELYNN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Evelynn.png',
    EZREAL:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Ezreal.png',
    FIDDLESTICKS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Fiddlesticks.png',
    FIORA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Fiora.png',
    FIZZ:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Fizz.png',
    GALIO:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Galio.png',
    GANGPLANK:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Gangplank.png',
    GAREN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Garen.png',
    GNAR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Gnar.png',
    GRAGAS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Gragas.png',
    GRAVES:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Graves.png',
    GWEN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Gwen.png',
    HECARIM:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Hecarim.png',
    HEIMERDINGER:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Heimerdinger.png',
    ILLAOI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Illaoi.png',
    IRELIA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Irelia.png',
    IVERN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Ivern.png',
    JANNA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Janna.png',
    JARVANIV:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/JarvanIV.png',
    JAX:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Jax.png',
    JAYCE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Jayce.png',
    JHIN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Jhin.png',
    JINX:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Jinx.png',
    KSANTE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/KSante.png',
    KAISSA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Kaisa.png',
    KALISTA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Kalista.png',
    KARMA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Karma.png',
    KARTHUS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Karthus.png',
    KASSADIN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Kassadin.png',
    KATARINA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Katarina.png',
    KAYLE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Kayle.png',
    KAYN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Kayn.png',
    KENNEN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Kennen.png',
    KHAZIX:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/KhaZix.png',
    KINDRED:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Kindred.png',
    KLED:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Kled.png',
    KOGMAW:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/KogMaw.png',
    LEBLANC:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/LeBlanc.png',
    LEESIN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/LeeSin.png',
    LEONA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Leona.png',
    LILLIA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Lillia.png',
    LISSANDRA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Lissandra.png',
    LUCIAN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Lucian.png',
    LULU:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Lulu.png',
    LUX:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Lux.png',
    MALPHITE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Malphite.png',
    MALZAHAR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Malzahar.png',
    MAOKAI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Maokai.png',
    MASTERYI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/MasterYi.png',
    MISSFORTUNE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/MissFortune.png',
    MORDEKAISER:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Mordekaiser.png',
    MORGANA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Morgana.png',
    NAMI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Nami.png',
    NASUS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Nasus.png',
    NAUTILUS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Nautilus.png',
    NEKKO:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Nekko.png',
    NIDALEE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Nidalee.png',
    NILAH:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Nilah.png',
    NOCTURNE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Nocturne.png',
    NUNUWILLUMP:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/NunuWillump.png',
    OLAF:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Olaf.png',
    ORIANNA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Orianna.png',
    ORNN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Ornn.png',
    PANTHEON:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Pantheon.png',
    POPPY:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Poppy.png',
    PYKE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Pyke.png',
    QIYANA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Qiyana.png',
    QUINN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Quinn.png',
    RAKAN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Rakan.png',
    RAMMUS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Rammus.png',
    REKSAI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/RekSai.png',
    RELL:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Rell.png',
    RENATAGLASC:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Renata.png',
    RENEKTON:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Renekton.png',
    RENGAR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Rengar.png',
    RIVEN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Riven.png',
    RUMBLE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Rumble.png',
    RYZE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Ryze.png',
    SAMIRA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Samira.png',
    SEJUANI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Sejuani.png',
    SENNA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Senna.png',
    SERAPHINE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Seraphine.png',
    SETT:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Sett.png',
    SHACO:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Shaco.png',
    SHEN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Shen.png',
    SHYVANA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Shyvana.png',
    SINGED:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Singed.png',
    SION:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Sion.png',
    SIVIR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Sivir.png',
    SKARNER:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Skarner.png',
    SONA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Sona.png',
    SORAKA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Soraka.png',
    SWAIN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Swain.png',
    SYLAS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Sylas.png',
    SYNDRA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Syndra.png',
    TAHMKENCH:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/TahmKench.png',
    TALIYAH:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Taliyah.png',
    TALON:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Talon.png',
    TARIC:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Taric.png',
    TEEMO:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Teemo.png',
    THRESH:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Thresh.png',
    TRISTANA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Tristana.png',
    TRUNDLE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Trundle.png',
    TRYNDAMERE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Tryndamere.png',
    TWISTEDFATE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/TwistedFate.png',
    TWITCH:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Twitch.png',
    UDYR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Udyr.png',
    URGOT:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Urgot.png',
    VARUS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Varus.png',
    VAYNE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Vayne.png',
    VEIGAR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Veigar.png',
    VELKOZ:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/VelKoz.png',
    VEX:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Vex.png',
    VI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Vi.png',
    VIEGO:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Viego.png',
    VIKTOR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Viktor.png',
    VLADIMIR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Vladimir.png',
    VOLIBEAR:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Volibear.png',
    WARWICK:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Warwick.png',
    WUKONG:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Wukong.png',
    XAYAH:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Xayah.png',
    XERATH:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Xerath.png',
    XINZHAO:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/XinZhao.png',
    YASUO:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Yasuo.png',
    YONE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Yone.png',
    YORICK:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Yorick.png',
    YUUMI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Yuumi.png',
    ZAC:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Zac.png',
    ZED:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Zed.png',
    ZERI:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Zeri.png',
    ZIGGS:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Ziggs.png',
    ZILEAN:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Zilean.png',
    ZOE:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Zoe.png',
    ZYRA:
      'https://raw.githubusercontent.com/DeeFreitas/Don-tEndOnALoss/main/assets/Zyra.png',
    NOIMG:
      'https://ddragon.leagueoflegends.com/cdn/11.13.1/img/profileicon/29.png',
  };